# Imports

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np
import os
import sys
import matplotlib.pyplot as plt
import pickle
import pandas as pd
pd.set_option('display.max_columns', 200)

import tensorflow as tf
tf.compat.v1.enable_eager_execution()
from tensorflow import keras
print(tf.__version__)
import model_fns as mfn

from card import Card
from board import Board
from player import Player
from rule import Rule
import optimal_strategy as opt

import multiprocessing
import time
from multiprocessing.pool import ThreadPool
import threading
from tqdm import notebook
notebook.tqdm.pandas()

from euchre_lib import *
from search_lib import *
import data_formatting as dtf

1.15.3


In [3]:
notebook.tqdm.get_lock().locks = []

# Create dataset

In [211]:
#os.system('rm -r RLdataset/*')

0

In [212]:
mx_thresh = 72; N_CPUS = 8
thresholds = [mx_thresh]*N_CPUS
n_hands = int(1e4)
n_epochs = 100
# get 8 million = 8e6 = 8 CPUS x 1e4 hands x 1e2 epochs
# estimate it takes 35 minutes, given 500 hands/sec
# actually more like 90-100 minutes, eh
if not os.path.exists(os.path.join(os.getcwd(), 'RLdataset')):
    os.mkdir(os.path.join(os.getcwd(), 'RLdataset'))

In [213]:
parallel_search_wrapper(thresholds, MAX_CPUS=N_CPUS, n_epochs=n_epochs, n_hands=n_hands,\
                        opp_thresh=mx_thresh, title='Making dataset', folder='RLdataset')

Making dataset:   0%|          | 0/100 [00:00<?, ?it/s]

Making dataset:   0%|          | 0/100 [00:00<?, ?it/s]

Making dataset:   0%|          | 0/100 [00:00<?, ?it/s]

Making dataset:   0%|          | 0/100 [00:00<?, ?it/s]

Making dataset:   0%|          | 0/100 [00:00<?, ?it/s]

Making dataset:   0%|          | 0/100 [00:00<?, ?it/s]

Making dataset:   0%|          | 0/100 [00:00<?, ?it/s]

Making dataset:   0%|          | 0/100 [00:00<?, ?it/s]

Done!
This took 4722.23 seconds
This took 78.70 minutes


In [ ]:
#def parallel_search_wrapper(thresholds, MAX_CPUS=8, n_epochs=10, n_hands=100, opp_thresh=None,
#                            title=None, ROOT_DIR=os.getcwd()+'/', folder=None):

# Format Data

In [6]:
infolder = os.path.join(os.getcwd(), 'RLdataset')
#infolder = os.path.join(os.getcwd(), 'thresholds', 'thresh70')
data = read_all_hands(infolder)
data.shape

  0%|          | 0/100 [00:00<?, ?it/s]

(1000000, 122)

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Columns: 122 entries, p0c1 to p3trueid
dtypes: int64(101), object(21)
memory usage: 930.8+ MB


In [8]:
data.head()

p0c1  p0c1isD  p0c1isH  p0c1isS  p0c2  p0c2isD  p0c2isH  p0c2isS  p0c3  \
0    20        0        1        0    12        0        1        0    10   
1    30        0        0        0    15        0        0        0     4   
2     3        0        0        0     5        0        1        0    10   
3    35        0        0        0    30        0        0        0    12   
4    10        0        0        0     4        0        0        0    10   

   p0c3isD  p0c3isH  p0c3isS  p0c4  p0c4isD  p0c4isH  p0c4isS  p0c5  p0c5isD  \
0        0        0        0     1        0        0        0     2        0   
1        0        1        0     2        0        1        0    10        0   
2        0        0        1     5        0        0        1     1        0   
3        0        0        0    10        1        0        0     1        0   
4        1        0        0     2        0        1        0     1        0   

   p0c5isH  p0c5isS  p1c1  p1c1isD  p1c1isH  p1c1isS  p1c2  p1c2isD  p1c2isH  \
0        0        1    35        0        1        0    31        1        0   
1        0        1    20        0        0        0     5        1        0   
2        0        1    30        1        0        0    25        1        0   
3        1        0     5        1        0        0     4        1        0   
4        1        0     5        1        0        0     4        1        0   

   p1c2isS  p1c3  p1c3isD  p1c3isH  p1c3isS  p1c4  p1c4isD  p1c4isH  p1c4isS  \
0        0     4        0        0        0     3        0        0        0   
1        0     2        1        0        0     5        0        0        1   
2        0    20        1        0        0    12        1        0        0   
3        0    10        0        1        0     4        0        1        0   
4        0     1        1        0        0     5        0        1        0   

   p1c5  p1c5isD  p1c5isH  p1c5isS  p2c1  p2c1isD  p2c1isH  p2c1isS  p2c2  \
0     1        0        0        1    10        1        0        0     4   
1     4        0        0        1    31        0        0        1    10   
2     2        0        1        0    31        0        1        0    10   
3    10        0        0        1    15        0        0        0     2   
4     4        0        1        0    31        0        0        0    25   

   p2c2isD  p2c2isH  p2c2isS  p2c3  p2c3isD  p2c3isH  p2c3isS  p2c4  p2c4isD  \
0        1        0        0     1        1        0        0     5        0   
1        1        0        0     3        1        0        0     5        0   
2        0        0        0     2        0        0        0     4        0   
3        1        0        0     3        0        1        0     5        0   
4        0        0        1     2        0        0        0     1        0   

   p2c4isH  p2c4isS  p2c5  p2c5isD  p2c5isH  p2c5isS  p3c1  p3c1isD  p3c1isH  \
0        0        1     4        0        0        1    30        0        1   
1        1        0     2        0        0        1    35        0        0   
2        1        0     2        0        0        1    35        1        0   
3        0        1     4        0        0        1    31        0        0   
4        0        0     3        0        1        0    30        0        0   

   p3c1isS  p3c2  p3c2isD  p3c2isH  p3c2isS  p3c3  p3c3isD  p3c3isH  p3c3isS  \
0        0     5        1        0        0     2        1        0        0   
1        0    12        0        0        0     1        1        0        0   
2        0     4        0        0        0     1        0        0        0   
3        1     3        1        0        0     5        0        1        0   
4        1    20        0        0        1    12        0        0        1   

   p3c4  p3c4isD  p3c4isH  p3c4isS  p3c5  p3c5isD  p3c5isH  p3c5isS  TC_power  \
0    10        0        0        1     3        0        0        1        15   
1     3        0        1    

In [9]:
p0hand = ['JH', 'JD', 'QC', 'JC', '9S']
p1hand = ['AD', 'QD', '9D', 'KS', 'QS']
p2hand = ['AH', 'KD', 'TD', 'AS', 'JS']
p3hand = ['QH', '9H', 'AC', '9C', 'TS'] + ['TH']

### Check that the data formatting functions work properly

In [159]:
# this seems to be working just fine
group1_info = dtf.get_group1_info(data.iloc[1], 0, 0)
for arr in [group1_info[:4], group1_info[4:8], group1_info[8], group1_info[9], group1_info[10:14], group1_info[14:]]:
    print(arr)
z="""
    #######
    DATA GROUP 1: Calling trump
    #######
    (4)  1.) Who dealt (position relative to "me")
    (4)  2.) Who called trump (position relative to "me")
    (1)  3.) Which round was trump called in
    (1)  4.) Going alone?
    (4)  5.) Which suit is trump (not sure if this one needs to be here)
    (10) 6.) What is the turn card
    Total: 24 columns
    """

[0 0 1 0]
[1 0 0 0]
1
0
[1 0 0 0]
[0 0 0 0 1 0 1 0 0 0]


In [149]:
# this seems to be working just fine
tnum = 4
group2_info = dtf.get_group2_info(data.iloc[0], tnum, 3)
for arr in [group2_info[:4], group2_info[4:8], group2_info[8:19], group2_info[19:30], group2_info[30:35], group2_info[35:]]:
    print(arr)
print('Led card:', data.iloc[0]['played'+str(4*tnum+1)])

z="""
    #######
    DATA GROUP 2: Other misc. information
    #######
    (4)  1.) Who is leading right now
    (4)  2.) Who is winning right now
    (11) 3.) What card was led (is it trump)
    (11) 4.) What card is winning (is it trump)
    (5)  5.) Which team won each trick so far (+1 for "me", 0 for no one (yet), -1 for opponents)
    (12) 6.) Any players confirmed short in any suits
    Total: 47 columns
    """

[1 0 0 0]
[0 0 1 0]
[1 0 0 0 0 0 0 0 0 1 0]
[0 0 0 0 0 1 0 0 0 1 0]
[-1 -1  1 -1  0]
[0 0 0 0 1 0 1 1 1 0 0 0]
Led card: 9S0


In [82]:
# this seems to be working just fine
num_cols = 13
group3_info = dtf.get_group3_info(data.iloc[0], 0, 0)
for i in range(num_cols):
    print(i, ': ', sum(group3_info[i::num_cols]))

print()
print(p3hand)
print()
cards = [c+s for s in list('CDHS') for c in list('9TJQKA')]
for i in range(24):
    print(cards[i], ': ', group3_info[(num_cols*i):(num_cols*(i+1))])
z="""
    #######
    DATA GROUP 3: All card locations (constant order: 9C, 10C, ..., (D), (H), ..., KS, AS)
    #######
    For each card (24):
    (4)  1.) Confirmed in anyone's hand (my hand + ordered up turn card?)
    (4)  2.) Played in a previous trick by someone (maybe later expand this to which prev trick?)
    (3)  3.) Played in CURRENT trick by someone
    (1)  4.) Confirmed buried
    (1)  5.) Is trump
    Total: 312 columns
    """

0 :  0
1 :  0
2 :  1
3 :  5
4 :  0
5 :  0
6 :  0
7 :  0
8 :  0
9 :  0
10 :  0
11 :  0
12 :  7

['QH', '9H', 'AC', '9C', 'TS', 'TH']

9C :  [0 0 0 0 0 0 0 0 0 0 0 0 0]
TC :  [0 0 0 0 0 0 0 0 0 0 0 0 0]
JC :  [0 0 0 1 0 0 0 0 0 0 0 0 0]
QC :  [0 0 0 1 0 0 0 0 0 0 0 0 0]
KC :  [0 0 0 0 0 0 0 0 0 0 0 0 0]
AC :  [0 0 0 0 0 0 0 0 0 0 0 0 0]
9D :  [0 0 0 0 0 0 0 0 0 0 0 0 0]
TD :  [0 0 0 0 0 0 0 0 0 0 0 0 0]
JD :  [0 0 0 1 0 0 0 0 0 0 0 0 1]
QD :  [0 0 0 0 0 0 0 0 0 0 0 0 0]
KD :  [0 0 0 0 0 0 0 0 0 0 0 0 0]
AD :  [0 0 0 0 0 0 0 0 0 0 0 0 0]
9H :  [0 0 0 0 0 0 0 0 0 0 0 0 1]
TH :  [0 0 1 0 0 0 0 0 0 0 0 0 1]
JH :  [0 0 0 1 0 0 0 0 0 0 0 0 1]
QH :  [0 0 0 0 0 0 0 0 0 0 0 0 1]
KH :  [0 0 0 0 0 0 0 0 0 0 0 0 1]
AH :  [0 0 0 0 0 0 0 0 0 0 0 0 1]
9S :  [0 0 0 1 0 0 0 0 0 0 0 0 0]
TS :  [0 0 0 0 0 0 0 0 0 0 0 0 0]
JS :  [0 0 0 0 0 0 0 0 0 0 0 0 0]
QS :  [0 0 0 0 0 0 0 0 0 0 0 0 0]
KS :  [0 0 0 0 0 0 0 0 0 0 0 0 0]
AS :  [0 0 0 0 0 0 0 0 0 0 0 0 0]


In [44]:
# this seems to be working just fine
group4_info = dtf.get_group4_info(data.iloc[0], 0, 0)
print(group4_info, '\n\n', p0hand, '\n\n', (np.argwhere(np.array(group4_info)==1).reshape(-1)+1)%11)

[0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0] 

 ['JH', 'JD', 'QC', 'JC', '9S'] 

 [ 4  7  3  9  0  3  8  0  3  7  1 10]


### Format the first 10k hands csv

In [221]:
folder = os.path.join(os.getcwd(), 'RLdataset')
first_group = pd.concat([pd.read_csv(os.path.join(folder, '10000_hands_'+str(i).zfill(3)+'.csv'))\
                         for i in notebook.tqdm(range(2))]).reset_index(drop=True)
first_group.head()

  0%|          | 0/2 [00:00<?, ?it/s]

p0c1  p0c1isD  p0c1isH  p0c1isS  p0c2  p0c2isD  p0c2isH  p0c2isS  p0c3  \
0    12        1        0        0     4        0        1        0     2   
1    35        0        0        1    20        0        0        1    10   
2     1        0        0        0     5        1        0        0     4   
3     2        0        0        1    30        0        0        0    20   
4     1        0        0        0     5        1        0        0     4   

   p0c3isD  p0c3isH  p0c3isS  p0c4  p0c4isD  p0c4isH  p0c4isS  p0c5  p0c5isD  \
0        0        1        0     1        0        1        0     1        0   
1        0        0        0     4        0        0        0    10        1   
2        1        0        0    10        0        1        0     4        0   
3        0        0        0    15        0        0        0     3        0   
4        0        1        0     3        0        1        0     2        0   

   p0c5isH  p0c5isS  p1c1  p1c1isD  p1c1isH  p1c1isS  p1c2  p1c2isD  p1c2isH  \
0        0        1    25        1        0        0     4        0        0   
1        0        0    30        0        0        1     3        1        0   
2        1        0    25        0        0        1     2        0        0   
3        1        0     4        0        0        1    12        0        0   
4        1        0    31        0        0        0    10        1        0   

   p1c2isS  p1c3  p1c3isD  p1c3isH  p1c3isS  p1c4  p1c4isD  p1c4isH  p1c4isS  \
0        0     3        0        0        0     5        0        1        0   
1        0    10        0        1        0     5        0        1        0   
2        0     3        1        0        0     1        1        0        0   
3        0     2        1        0        0     1        1        0        0   
4        0     4        1        0        0     2        1        0        0   

   p1c5  p1c5isD  p1c5isH  p1c5isS  p2c1  p2c1isD  p2c1isH  p2c1isS  p2c2  \
0     5        0        0        1    10        0        0        0     5   
1     3        0        1        0    31        0        0        0    15   
2     3        0        1        0    10        0        0        0     5   
3     1        0        1        0    35        0        0        0    25   
4     5        0        1        0    30        0        0        1    15   

   p2c2isD  p2c2isH  p2c2isS  p2c3  p2c3isD  p2c3isH  p2c3isS  p2c4  p2c4isD  \
0        0        0        0    10        0        0        1     3        0   
1        0        0        1     4        1        0        0     2        1   
2        0        0        0     4        0        0        0     5        0   
3        0        0        0     4        1        0        0     3        1   
4        0        0        1     5        0        0        0     4        0   

   p2c4isH  p2c4isS  p2c5  p2c5isD  p2c5isH  p2c5isS  p3c1  p3c1isD  p3c1isH  \
0        0        1     2        0        0        1    31        0        1   
1        0        0     1        0        1        0    25        0        0   
2        1        0     1        0        1        0    35        0        0   
3        0        0    10        0        1        0     5        0        0   
4        0        0    10        0        1        0    25        0        0   

   p3c1isS  p3c2  p3c2isD  p3c2isH  p3c2isS  p3c3  p3c3isD  p3c3isH  p3c3isS  \
0        0    15        1        0        0     2        0        0        0   
1        1     1        0        0        0     5        1        0        0   
2        1    31        0        0        0    15        0        0        1   
3        1     1        0        0        1    10        1        0        0   
4        1    12        0        0        1    10        0        0        0   

   p3c4  p3c4isD  p3c4isH  p3c4isS  p3c5  p3c5isD  p3c5isH  p3c5isS  TC_power  \
0    10        0        1        0     4        0        0        1        30   
1     1        1        0    

In [222]:
first_formatted = dtf.format_data(first_group)

  0%|          | 0/20000 [00:00<?, ?it/s]

KeyboardInterrupt: 

## Do the rest of the formatting on a HPC (see `format_data.sh`)

In [5]:
expected_count_comma = 122
def count_odd_lines(infile):
    with open(infile, 'r') as f:
        lines = f.read()
    
    weird_lines = [[i, len(line.split(','))] for i, line in enumerate(lines.split('\n')) if len(line.split(',')) != expected_count_comma]
    
    return weird_lines

In [321]:
for i in range(500, 797):
    file = 'RLdataset/10000_hands_' + str(i) + '.csv'
    weird_lines = count_odd_lines(file)
    if len(weird_lines) > 1:
        print(file+':', len(weird_lines), weird_lines[:5])

RLdataset/10000_hands_500.csv: 64 [[1340, 243], [1815, 244], [1870, 244], [1897, 247], [1924, 247]]
RLdataset/10000_hands_611.csv: 5 [[306, 125], [334, 123], [361, 243], [10000, 13], [10001, 1]]
RLdataset/10000_hands_666.csv: 52 [[698, 154], [725, 255], [752, 228], [780, 145], [807, 250]]


In [323]:
for i in range(500, 797):
    file = 'RLdataset/10000_hands_' + str(i) + '.csv'
    weird_lines = count_odd_lines(file)
    if len(weird_lines) > 1:
        print('Re-doing file %s' %file)
        with open(file, 'r') as infile:
            dirty = infile.read()
        
        clean = '\n'.join([line for line in dirty.split('\n') if len(line.split(',')) == expected_count_comma])
        with open(file, 'w') as outfile:
            outfile.write(clean)
        
        weird_lines = count_odd_lines(file)
        if len(weird_lines) > 1:
            print('ERROR IN CLEANING FILE %s' %file)

Re-doing file RLdataset/10000_hands_500.csv
Re-doing file RLdataset/10000_hands_611.csv
Re-doing file RLdataset/10000_hands_666.csv


# Define model fn

In [86]:
model = mfn.make_model()
#model.summary() # about 7.4 mil trainable parameters

In [5]:
%%time
TRAIN, VALID, TEST = mfn.train_valid_test()

CPU times: user 6.69 s, sys: 131 ms, total: 6.82 s
Wall time: 6.81 s


In [88]:
%%time
for data, target in TRAIN.take(1):
    print(data.shape, target.shape)
    break

(10, 438) (10, 24)
CPU times: user 9.03 s, sys: 257 ms, total: 9.29 s
Wall time: 9.27 s


In [ ]:
history = model.fit(
    TRAIN,
    epochs=10,
    validation_data=VALID,
    steps_per_epoch=int(1e5),
    validation_steps=int(1e4),
    callbacks = [keras.callbacks.ModelCheckpoint('models/model1_original.h5')]
)

Train for 100000 steps, validate for 10000 steps
Epoch 1/10
100000/100000 [==============================] - 632s 6ms/step - loss: 0.3754 - categorical_accuracy: 0.8798 - precision_4: 0.9057 - recall_4: 0.8591 - auc_4: 0.9940 - val_loss: 0.3151 - val_categorical_accuracy: 0.8914 - val_precision_4: 0.9086 - val_recall_4: 0.8719 - val_auc_4: 0.9967- precis
Epoch 2/10
100000/100000 [==============================] - 625s 6ms/step - loss: 0.1461 - categorical_accuracy: 0.9511 - precision_4: 0.9571 - recall_4: 0.9461 - auc_4: 0.9983 - val_loss: 0.2193 - val_categorical_accuracy: 0.9275 - val_precision_4: 0.9355 - val_recall_4: 0.9177 - val_auc_4: 0.9978
Epoch 3/10
100000/100000 [==============================] - 638s 6ms/step - loss: 0.1057 - categorical_accuracy: 0.9647 - precision_4: 0.9684 - recall_4: 0.9615 - auc_4: 0.9988 - val_loss: 0.1721 - val_categorical_accuracy: 0.9433 - val_precision_4: 0.9484 - val_recall_4: 0.9376 - val_auc_4: 0.9981
Epoch 4/10
100000/100000 [=================

----------

How big actually are the train / valid datasets? They have ~400 columns each, and there's about $800 \times 10^4$ hands, giving roughly 160 million cards played. Of these, about 50% are single-option, so we cut this size in roughly half. Then, 70% of the remainder (about 55 million hands) goes into train, 20% of this goes into validation (about 16 million hands), and the final 10% (about 8 million hands) goes into test.

----------

In [11]:
model = mfn.make_model(dense_layers=[8, 6, 4, 2, 1, 0.5, 0.25])
#model.summary() # about 17.4 mil trainable parameters

In [12]:
history = model.fit(
    TRAIN,
    epochs=30,
    validation_data=VALID,
    steps_per_epoch=int(1e5),
    validation_steps=int(1e4),
    callbacks = [keras.callbacks.ModelCheckpoint('models/model4_big.h5')]
)

Train for 100000 steps, validate for 10000 steps
Epoch 1/30
100000/100000 [==============================] - 765s 8ms/step - loss: 0.3866 - categorical_accuracy: 0.8782 - precision_5: 0.9080 - recall_5: 0.8553 - auc_5: 0.9937 - val_loss: 0.3130 - val_categorical_accuracy: 0.8917 - val_precision_5: 0.9064 - val_recall_5: 0.8751 - val_auc_5: 0.9965
Epoch 2/30
100000/100000 [==============================] - 743s 7ms/step - loss: 0.1433 - categorical_accuracy: 0.9526 - precision_5: 0.9589 - recall_5: 0.9473 - auc_5: 0.9983 - val_loss: 0.2100 - val_categorical_accuracy: 0.9306 - val_precision_5: 0.9388 - val_recall_5: 0.9226 - val_auc_5: 0.9973
Epoch 3/30
100000/100000 [==============================] - 746s 7ms/step - loss: 0.1019 - categorical_accuracy: 0.9661 - precision_5: 0.9700 - recall_5: 0.9628 - auc_5: 0.9989 - val_loss: 0.1754 - val_categorical_accuracy: 0.9441 - val_precision_5: 0.9508 - val_recall_5: 0.9369 - val_auc_5: 0.9979
Epoch 4/30
100000/100000 [=========================

# Which ones does the model mispredict?

In [4]:
model = keras.models.load_model('models/model4_big.h5')

In [5]:
def get_mispredicts(model, test, prnt=True, every=int(1e4)):
    missed_data, missed_target, missed_pred = [], [], []
    skipcount = len(pd.read_csv('missed_target.csv')) if os.path.exists('missed_target.csv') else 0
    
    for i, (data, target) in enumerate(test):
        if i < skipcount:
            continue
        if i % every == 0:
            if i > 0:
                for filename, arr in zip(['missed_'+f+'.csv' for f in ['data', 'target', 'pred']], [missed_data, missed_target, missed_pred]):
                    with open(filename, 'a') as f:
                        for line in arr:
                            f.write(','.join([str(int(v)) for v in line]))
                            f.write('\n')
                return missed_data, missed_target, missed_pred
                missed_data, missed_target, missed_pred = [], [], []
            if prnt:
                if i != 0:
                    print('Predicting %i (dt = %.1f seconds)...' %(i, time.time()-t_checkpoint))
                else:
                    print('Predicting %i...' %i)
                t_checkpoint = time.time()
    
        
        ypred = model.predict(data)
        for i in range(len(ypred)):
            ypred[i] = [0 if ypred[i][j] != ypred[i].max() else 1 for j in range(len(ypred[i]))]
            correct = sum(ypred[i]-target[i]).numpy() == 0
            if not correct:
                missed_data.append(data[i].numpy())
                missed_target.append(target[i].numpy())
                missed_pred.append(ypred[i])
                
    print('Missed a total of %.1f%% (%i / %i)' %(len(missed_pred)/i*100, len(missed_pred), i))
    return missed_data, missed_target, missed_pred    

In [24]:
%%time
seed = 623
TRAIN, VALID, TEST = mfn.train_valid_test(seed=seed)
missed_data, missed_target, missed_pred = get_mispredicts(model, TEST)

Predicting 0...
CPU times: user 16min 17s, sys: 1min 14s, total: 17min 32s
Wall time: 12min 43s


In [33]:
missed_one = False
count = 0
tstart = time.time()
while not missed_one and time.time()-tstart < 60*30:
    for data, target in TEST.take(100):
        ypred = model.predict(data)
        for i in range(len(ypred)):
            ypred[i] = [0 if ypred[i][j] != ypred[i].max() else 1 for j in range(len(ypred[i]))]
            correct = sum(ypred[i]-target[i]).numpy() == 0
            count += 1
            if not correct:
                print(np.argwhere(ypred[i]==1), np.argwhere(target[i].numpy()==1), correct)
                missed_one = True
print(count, time.time()-tstart)

132000 1803.112186908722


In [34]:
missed_one = False
count = 0
tstart = time.time()
while not missed_one and time.time()-tstart < 60*30:
    for data, target in VALID.take(100):
        ypred = model.predict(data)
        for i in range(len(ypred)):
            ypred[i] = [0 if ypred[i][j] != ypred[i].max() else 1 for j in range(len(ypred[i]))]
            correct = sum(ypred[i]-target[i]).numpy() == 0
            count += 1
            if not correct:
                print(np.argwhere(ypred[i]==1), np.argwhere(target[i].numpy()==1), correct)
                missed_one = True
print(count, time.time()-tstart, missed_one)

129000 1804.4597928524017 False


# Does it really mispredict none?

In [35]:
history = model.fit(
    TRAIN,
    epochs=1,
    validation_data=VALID,
    steps_per_epoch=int(1e4),
    validation_steps=int(1e3),
    #callbacks = [keras.callbacks.ModelCheckpoint('models/model4_big.h5')]
)

Train for 10000 steps, validate for 1000 steps
10000/10000 [==============================] - 87s 9ms/step - loss: 0.0228 - categorical_accuracy: 0.9925 - precision_5: 0.9929 - recall_5: 0.9923 - auc_5: 0.9997 - val_loss: 0.0572 - val_categorical_accuracy: 0.9814 - val_precision_5: 0.9824 - val_recall_5: 0.9806 - val_auc_5: 0.9993


In [52]:
for i, (data, target) in enumerate(TEST.take(20)):
    m = tf.keras.metrics.CategoricalAccuracy()
    m.update_state(target, model.predict(data))
    print(i, ':\t', m.result().numpy())
    print(target.numpy().argmax(axis=-1))
    print(model.predict(data).argmax(axis=-1))
    print()
    
    correct = np.all(model.predict(data).argmax(axis=-1) == target.numpy().argmax(axis=-1))
    if not correct:
        print('DING')

0 :	 1.0
[ 9 23  8 22 17  1 18 23 17  3]
[ 9 23  8 22 17  1 18 23 17  3]

1 :	 1.0
[ 6  3 20  1  0 22 10  0 17 23]
[ 6  3 20  1  0 22 10  0 17 23]

2 :	 1.0
[ 0  0 15  5 15 23 12 16 15  3]
[ 0  0 15  5 15 23 12 16 15  3]

3 :	 1.0
[ 6 20 17  5  2 15 21 20 11 16]
[ 6 20 17  5  2 15 21 20 11 16]

4 :	 1.0
[ 9 15 18 11  7  5  3  2  8 13]
[ 9 15 18 11  7  5  3  2  8 13]

5 :	 1.0
[ 5 23 10  9  8 14 18 22 10 15]
[ 5 23 10  9  8 14 18 22 10 15]

6 :	 1.0
[ 4  7 10 20 18  0 19 15 21 13]
[ 4  7 10 20 18  0 19 15 21 13]

7 :	 1.0
[19  4 15 15 21  7  6  6 16  3]
[19  4 15 15 21  7  6  6 16  3]

8 :	 1.0
[17 15  2 20 15  2 15 16 11  1]
[17 15  2 20 15  2 15 16 11  1]

9 :	 1.0
[21 12  2  6  5 16 23  1  7 11]
[21 12  2  6  5 16 23  1  7 11]

10 :	 1.0
[11  0 22 22  9 23 11 19  9  0]
[11  0 22 22  9 23 11 19  9  0]

11 :	 1.0
[14 22 21 18  1 10  1  4  6 22]
[14 22 21 18  1 10  1  4  6 22]

12 :	 1.0
[20 13 12 19  6  6  5 11 14 13]
[20 13 12 19  6  6  5 11 14 13]

13 :	 1.0
[21 20 18 21 23 20 15  0 

# Try this again....

In [6]:
def get_mispredicts_v2(model, test, prnt=True, every=int(1e4)):
    missed_data, missed_target, missed_pred = [], [], []
    skipcount = len(pd.read_csv('missed_target.csv'))/(0.02*10) if os.path.exists('missed_target.csv') else 0
    test = test.skip(int(skipcount))
    filenames = ['missed_'+f+'.csv' for f in ['data', 'target', 'pred']]
    t_checkpoint = time.time()
    
    for i, (data, target) in enumerate(test):
        if i == 0: print('Starting the loop...')
        #if i < skipcount: continue
        if i % every == 0:
            if len(missed_data) > 0:
                print('Writing out %i misses...' %len(missed_data))
                for filename, arr in zip(filenames, [missed_data, missed_target, missed_pred]):
                    with open(filename, 'a') as f:
                        for line in arr:
                            f.write(','.join([str(int(v)) for v in line]))
                            f.write('\n')
                missed_data, missed_target, missed_pred = [], [], []
            if prnt:
                if i != 0:
                    print('Predicting %i (dt = %.1f seconds)...' %(i, time.time()-t_checkpoint))
                else:
                    print('Predicting %i...' %i)
                t_checkpoint = time.time()
                    
        ypred = model.predict(data)
        corrects = ypred.argmax(axis=-1) == target.numpy().argmax(axis=-1)
        for j in range(len(corrects)):
            if not corrects[j]:
                missed_data.append(data[j])
                missed_target.append(target[j])
                missed_pred.append(ypred[j])
                #print('FOUND ONE: %i' %i)
    
    if len(missed_data) > 0:
        for filename, arr in zip(filenames, [missed_data, missed_target, missed_pred]):
            with open(filename, 'a') as f:
                for line in arr:
                    f.write(','.join([str(int(v)) for v in line]))
                    f.write('\n')
    return missed_data, missed_target, missed_pred

In [ ]:
%%time
seed = 623
TRAIN, VALID, TEST = mfn.train_valid_test(seed=seed)
print('Done loading datasets!')
missed_data, missed_target, missed_pred = get_mispredicts_v2(model, TEST, every=int(1e3))


Done loading datasets!
Starting the loop...
Predicting 0...
Writing out 225 misses...
Predicting 1000 (dt = 41.5 seconds)...
Writing out 203 misses...
Predicting 2000 (dt = 29.5 seconds)...
Writing out 191 misses...
Predicting 3000 (dt = 28.8 seconds)...
Writing out 208 misses...
Predicting 4000 (dt = 29.9 seconds)...
Writing out 206 misses...
Predicting 5000 (dt = 30.1 seconds)...
Writing out 212 misses...
Predicting 6000 (dt = 29.7 seconds)...
Writing out 220 misses...
Predicting 7000 (dt = 31.3 seconds)...
Writing out 213 misses...
Predicting 8000 (dt = 29.9 seconds)...
Writing out 206 misses...
Predicting 9000 (dt = 36.5 seconds)...
Writing out 191 misses...
Predicting 10000 (dt = 28.4 seconds)...
Writing out 210 misses...
Predicting 11000 (dt = 30.9 seconds)...
Writing out 169 misses...
Predicting 12000 (dt = 26.7 seconds)...
Writing out 178 misses...
Predicting 13000 (dt = 27.6 seconds)...
Writing out 217 misses...
Predicting 14000 (dt = 31.9 seconds)...
Writing out 205 misses..